# openapi2-run.yaml
# API configuration file for my-api 
swagger: '2.0'
info:
  title: myapi crc-api
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: #public API gateway URL goes here
paths:
  /test:
    get:
      summary: Total number of visitors
      operationId: test
      x-google-backend:
        address: #public API gateway URL goes here 
      responses:
        '200':
          description: A successful response
          schema:
            type: string
